# Generated by Django 5.2.3 on 2025-08-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0003_gameuser_animal_description_alter_animal_image'),
    ]

    operations = [
    ]
